name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VS_VERSION: '2022'
  BUILD_TYPE: 'Release'

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - {arch: x86, cxx_std: 17}
          - {arch: x64, cxx_std: 17}
          - {arch: x86, cxx_std: 20}
          - {arch: x64, cxx_std: 20}
          - {arch: x86, cxx_std: 23}
          - {arch: x64, cxx_std: 23}
    env:
      BUILD_ARCH: ${{ matrix.config.arch }}
      CXX_STD: ${{ matrix.config.cxx_std }}
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ci\build.ps1
